name: Bug report
description: Report a reproducible problem in the project
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail for us to reproduce and fix it quickly.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to trigger the bug
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, and relevant package versions
      placeholder: macOS 14, Python 3.12.5, social-network-graph-system 0.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant output/logs
      description: Paste traceback, CI failure output, or command output
      render: shell
