name: Feature request
description: Propose an enhancement to the project
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement. Please focus on the user outcome and practical scope.

  - type: input
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: It is difficult to ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred approach
      placeholder: We should add ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches considered

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is complete?
      placeholder: |
        - [ ] ...
        - [ ] ...

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
